import { createElement } from 'lwc';
import IDP_homePicklistCompV2 from 'c/iDP_homePicklistCompV2';

describe('c-i-d-p-home-picklist-comp-v-2', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-i-d-p-home-picklist-comp-v-2', {
            is: IDP_homePicklistCompV2
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});